/* Manejo de errores con try catch */
let numero1 = 20;
let numero3 = 30;

/*console.log(numero1);
console.log(numero2);
console.log(numero3);*/

console.log(numero1);
try{
	console.log(numero2);
}catch(error){
	console.log(error);
};

console.log(numero3);